### ISSUE TITLE
Arreglo de errores para poder subirlo a producción 

### ISSUE THREAD

**Issue by EvangeRodriguez** [sebastian-riggio/CRMF5#12]

**Comment by devctor** [comment]
Dejo el link a posible solucion del deploy.
Cuando se cambia de pagina nos da "404 NOT:_Found"
https://stackoverflow.com/questions/75846073/vercel-reactjs-vite-returning-404-on-page-refresh

**Comment by devctor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DEPLOY](https://trello.com/c/9mw3OPN6/44-deploy)
