### ISSUE TITLE
SPRINT CERO - CONFIGURACIÓN DE ENTORNO

### ISSUE THREAD

**Issue by EvangeRodriguez** [sebastian-riggio/CRMF5#2]

**Comment by HuilenPe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configuración de Playwright](https://trello.com/c/jZab9s0T/50-configuraci%C3%B3n-de-playwright)

**Comment by HuilenPe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crear una página de inicio de sesión.](https://trello.com/c/5Ib8cIsb/51-crear-una-p%C3%A1gina-de-inicio-de-sesi%C3%B3n)

**Comment by Arielparicio28** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tablas BBDD (diseño-relaciones)](https://trello.com/c/YKOIRoH1/32-tablas-bbdd-dise%C3%B1o-relaciones)

**Comment by HuilenPe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Como usuario quiero poder visualizar el menú dónde tenga la opción de elegir proyectos y convocatorias](https://trello.com/c/TFH0ZQZK/68-como-usuario-quiero-poder-visualizar-el-men%C3%BA-d%C3%B3nde-tenga-la-opci%C3%B3n-de-elegir-proyectos-y-convocatorias)

**Comment by HuilenPe** [comment]
**IMPORTANTE!:** 

- [ ] hacer revisión de lógica de Admin en el Frontend

**Comment by HuilenPe** [comment]
**valorar si el search es necesario en navbar:**

- [ ] falta logica de search
- [ ] falta acomodarlo en vista desktop, en la transición queda raro
