### ISSUE TITLE
Gestión proyectos

### ISSUE THREAD

**Issue by HuilenPe** [sebastian-riggio/CRMF5#3]

**Comment by sebastian-riggio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Diseñar y desarrollar una página de creación de proyectos que incluya campos para nombre del proyecto, departamento gestor, presupuesto global y presupuesto aportado por Factoría F5.](https://trello.com/c/Q7H0KjI4/80-dise%C3%B1ar-y-desarrollar-una-p%C3%A1gina-de-creaci%C3%B3n-de-proyectos-que-incluya-campos-para-nombre-del-proyecto-departamento-gestor-presup)

**Comment by EvangeRodriguez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visualización de un proyecto](https://trello.com/c/RvznrJco/83-visualizaci%C3%B3n-de-un-proyecto)
