### ISSUE TITLE
Modificaciones generales de frontend 

### ISSUE THREAD

**Issue by EvangeRodriguez** [sebastian-riggio/CRMF5#9]
Arreglos generales de frontend, estilos, etc. NO vamos a subir conexiones de frontend y backend. Solo estilos.

**Comment by HuilenPe** [comment]
**PENDIENTES**

- [ ] En los Nav ver fuentes
- [ ] Home Dashboard completo
- [ ] Mobile first
- [ ] dar funcionalidad a change theme
- [ ] avatar
- [ ] profile

**Comment by HuilenPe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(FRONT)Diseñar la página de inicio que mostrará el calendario de próximas convocatorias abiertas. / Crear una interfaz de usuario atractiva y fácil de usar para el calendario.](https://trello.com/c/WITuqyt9/120-frontdise%C3%B1ar-la-p%C3%A1gina-de-inicio-que-mostrar%C3%A1-el-calendario-de-pr%C3%B3ximas-convocatorias-abiertas-crear-una-interfaz-de-usuario-atr)

**Comment by EvangeRodriguez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [La página de detalles de una convocatoria debe incluir un botón de "Volver a la lista/VOLVER ATRAS" que permita a los usuarios regresar fácilmente a la lista principal.](https://trello.com/c/uDk2v3oK/131-la-p%C3%A1gina-de-detalles-de-una-convocatoria-debe-incluir-un-bot%C3%B3n-de-volver-a-la-lista-volver-atras-que-permita-a-los-usuarios-reg)
